### PR TITLE
Remove "code" from examples for blocks containing inlines

### PR DESCRIPTION
**Pull request by mgeier**
Code blocks don't have inline content, right?

AFAIU they have a third type of content, but that's probably not worth mentioning (and coming up with a name for).

### CODE REVIEW

**Comment by fiveop** [comment]
Those are not examples of blocks containing inline content, but examples for inline content. Code spans are inline content.

**Comment by jgm** [comment]
@fiveop is right, I don't see a problem here that needs fixing.
Closing this.

**Comment by mgeier** [comment]
I indeed wasn't thinking about *code spans*. Even more reason to clarify this!

@jgm Can you please re-open?

The problem with understanding this is that the enumeration is not complete. OTOH, it's not claiming to be.

AFAIU, there are three types of blocks, only two of which are mentioned in this sentence:

1. blocks that contain other blocks
2. blocks that contain inline content
3. blocks that contain some other stuff, namely code blocks and HTML blocks

Can't you see that there is potential for misunderstanding?

In my original comment I thought that the third type is not worth mentioning, but probably it is?

**Comment by mgeier** [comment]
I knew I forgot something! There seems to be a fourth type:

4. blocks that contain nothing, e.g. thematic break

But probably this can be seen as special case of the third type ...

**Comment by jgm** [comment]
I didn't mean this as an exhaustive list, but I agree it
could be clearer that there's a third category of blocks
elements -- those that contain neither inlines nor blocks.
However, the PR you submitted doesn't address this concern.
Submit a new PR that does?

+++ Matthias Geier [Apr 23 17 01:59 ]:

**Comment by mgeier** [comment]
I added a PR that fixes the original issue: #462.

The rest of the paragraph being not exact enough for a formal specification is a larger problem, I'll probably tackle that at a later time, but don't hold your breath.

**Pull request closed without merging**
