### PR TITLE
thematic break: non-whitespace -> non-space

### PR DESCRIPTION
**Pull request by mgeier**

### CODE REVIEW

**Comment by jgm** [comment]
I think the present wording is fine.  It's true that all the non-whitespace characters must be the same, isn't it?  Saying "non-space" might be confusing because you can have tabs.

**Comment by mgeier** [comment]
But that's the whole point of this PR! I wanted to make it less confusing!

According to the [spec](http://spec.commonmark.org/0.25/#thematic-breaks), a thematic break can have:

> ... any number of spaces, ...

There's no word about "whitespace", or did I miss this?

If you want to allow tabs, I think it would be better to define "tab" and then refer to "spaces" and/or "tabs". Those are only 2 out of 6 possible "whitespace characters".
You should also make an example with tabs in that case.

**Comment by jgm** [comment]
See the beginning of 2.2: "Tabs in lines are not expanded to
spaces. However, in contexts where indentation is
significant for the document’s structure, tabs behave as if
they were replaced by spaces with a tab stop of 4
characters."

Originally we just expanded tabs to spaces, so the spec was
written on the assumption that there were no tabs.  We
changed that later, so that you could have tabs in code
blocks, but didn't go through the spec exhaustively
inserting references to tabs; instead, there's the blanket
statement in 2.2.

I agree that it would be good to have an example using a
tab here, and maybe some rewording.

+++ Matthias Geier [Jun 26 16 01:05 ]:

**Comment by mgeier** [comment]
I didn't know that tabs are allowed in thematic breaks.

Where exactly should tabs be allowed?

> ... in contexts where indentation is significant for the document’s structure ...

As far as I understand this (and mind you, I'm not a native speaker!), a thematic break is no such context. I thought this was mainly about indentation in lists, and probably about indented code blocks.

I think the wording should definitely be changed!

Apart from that, I think it would be really helpful if the usage of tabs in place of spaces would be explicitly mentioned throughout the spec.

**Comment by jgm** [comment]
+++ Matthias Geier [Jun 27 16 09:00 ]:
>   I didn't know that tabs are allowed in thematic breaks.
>
>   Where exactly should tabs be allowed?
>
>     ... in contexts where indentation is significant for the document’s
>     structure ...
>
>   As far as I understand this (and mind you, I'm not a native speaker!),
>   a thematic break is no such context. I thought this was mainly about
>   indentation in lists, and probably about indented code blocks.

You're right.  We should say something explicitly about tabs
there.  Really we need to go through the whole document and
think about other places where tabs should be mentioned.

If you'd like to help identify such places, that would be
useful!

**Comment by jgm** [comment]
This is embarassing, but I realized that the reference implementations do in fact require spaces.
This should be changed.  They also require a space, not a tab, after the `#` in ATX headings.  Perhaps there are other places that still need fine-tuning now that we no longer expand tabs to spaces.

**Comment by jgm** [comment]
I've reverted the changes for now.  The issue needs more thought.  Putting in explicit language about tabs (and examples including tabs) everywhere we talk about spaces would certainly clutter things up a lot, perhaps hiding what is important in a forest of details.

On the other hand, the explicit statement at the beginning of the tabs section, "... in contexts where indentation is significant for the document’s structure ...", is not adequate because it doesn't cover ATX headers or thematic breaks (where, I agree, we should be liberal in allowing tabs where spaces can go).

I wonder if something like the following could work?  We define a notion of "space" for use in the spec which is a kind of "virtual space."  A space is either a literal SPACE character or one of the virtual spaces you'd get if a TAB were expanded to SPACEs.  (I don't know how to say this clearly yet.)  Then the spec can just talk about spaces.  This is, by the way, how the reference implementations do it; they count virtual spaces without actually expanding the tabs, so that literal tabs come out as literal tabs in your output.  Of course, it would still be good to include examples with tabs in places where we currently have examples for spaces.

**Comment by mgeier** [comment]
I don't think that defining yet another type of space (the "virtual space") will make the whole situation easier to grasp.
I think it's perfectly fine to mention "tabs or spaces" in several places where they are actually allowed.

What's the mental model one should have when looking at indentation of code blocks?
What happens when there are, e.g., two spaces followed by one tab followed by some "normal" letters?
Does the content of the code block have 2 spaces indentation or no indentation at all?
Or even a tab?

**Comment by jgm** [comment]
+++ Matthias Geier [Jul 04 16 08:19 ]:
>   I don't think that defining yet another type of space (the "virtual
>   space") will make the whole situation easier to grasp.
>   I think it's perfectly fine to mention "tabs or spaces" in several
>   places where they are actually allowed.

I've changed several things in a recent commit.   ATX
headers and thematic breaks now take tabs, and the general
language about tabs has been broadened to include those
cases.

>   What's the mental model one should have when looking at indentation of
>   code blocks?
>   What happens when there are, e.g., two spaces followed by one tab
>   followed by some "normal" letters?
>   Does the content of the code block have 2 spaces indentation or no
>   indentation at all?

Assuming the whole thing starts at the left edge or a tab
stop, then 2 spaces followed by a tab is equivalent to one
tab (given the 4-space tab stop).

The idea is that tabs behave just as if they'd been expanded
to spaces on a 4-space tab-stop, *except* that tabs that are
part of the content (e.g. spaces between words, parts of
code blocks, etc.) are preserved verbatim.  (In original
Markdown.pl, there was a destructive tab-to-space conversion
in the first phase, so you simply couldn't include a literal tab
in a code block, for example.  Bad for Makefiles!)

**Comment by mgeier** [comment]
Thanks, the situation is now a bit clearer to me, but there is still potential for improvement.

The definition of [ATX headings](http://spec.commonmark.org/0.26/#atx-headings) still only talks about "a space" and [thematic breaks](http://spec.commonmark.org/0.26/#thematic-breaks) only talk about "any number of spaces".

Thanks for the explanation regarding indented code blocks. I think I now understand how it is supposed to work, but I have the feeling that it is still not clear from the text of the spec alone.

**Comment by jgm** [comment]
+++ Matthias Geier [Jul 16 16 02:30 ]:
>   The definition of [1]ATX headings still only talks about "a space" and
>   [2]thematic breaks only talk about "any number of spaces".

True, but combine with this from the beginning of 2.2:
"However, in contexts where whitespace helps to define block
structure, tabs behave as if they were replaced by spaces
with a tab stop of 4 characters."

The current approach in the spec is only to talk of spaces,
and let this clause handle tabs.  We could switch to an
approach that explicitly talks of tabs everywhere  they can
go, but it would be a lot of changes and in some cases the
wording would have to be pretty complex.  So I haven't done
that, yet.

See
https://talk.commonmark.org/t/counterintuitive-interaction-of-tabstops-and-list-items/2169
for further discussion of the tabs issue.

**Pull request closed without merging**
